version: "2"
linters:
  default: all
  disable:
    - ireturn
    - nolintlint
    - tagliatelle
    - varnamelen
    - depguard
    - noinlineerr
  settings:
    wrapcheck:
      ignore-sigs:
        - .JSON
        - .NewHTTPError
        - .Redirect
        - .NoContent
        - .Errorf(
        - errors.New(
        - errors.Unwrap(
        - .Wrap(
        - .Wrapf(
        - .WithMessage(
        - .WithMessagef(
        - .WithStack(
